'use strict';
// tests for random
// Generated by serverless-mocha-plugin

const mod         = require('../index');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;
const data        = require('../../data.json');

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-random'
}

describe('random', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda
    wrapper.init(mod, {
      handler: 'random'
    });

    done()
  })

  describe('Passing invalid GET body', function() {
    it('results in success response', function(done) {
      wrapper.run({}, (err, response) => {
        expect(response).not.to.be.null;
        expect(err).to.be.null;
        expect(response.line).to.be.a.string;
        expect(data.random.indexOf(response.line)).to.be.gt(0);
        done();
      });
    });
  });
});

